name: James Fenn
description: James Fenn's photo collection.
url: "/photos"
baseurl: "/"

collections:
    images:
        output: true
    albums:
        output: true

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

include:
  - .scripts

sass:
    sass_dir: ./css
