name: James Fenn
description: James Fenn's photo collection.
url: https://jfenn.me/photos
baseurl: "/"

collections:
    images:
        output: false
    albums:
        output: true

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

include:
  - .scripts
